### ISSUE TITLE
Doesn't Uglify

### ISSUE THREAD

**Issue by thebarton** [ksylvest/jquery-growl#46]
I'm just using the basic gulp uglify and for some reason this plugin's js file doesn't uglify. Anyway to look at that?

**Comment by ksylvest** [comment]
@thebarton not sure - can you provide any more context?

**Comment by Zsavajji** [comment]
I got the same error too, by checking the latest published version it seems that your coffeeScript is now building into ES6.

**Comment by schmunk42** [comment]
```
Creating output bundle 'all':
  Compressing JavaScript files...
Parse error at /app/src/../web/bundles/common-temp.js.tmp:15764,10
    class Animation {
          ^
ERROR: Unexpected token: name (Animation)
    at JS_Parse_Error.get (eval at <anonymous> (/usr/lib/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:79:23)
    at fatal (/usr/lib/node_modules/uglify-js/bin/uglifyjs:271:52)
    at run (/usr/lib/node_modules/uglify-js/bin/uglifyjs:228:9)
    at Object.<anonymous> (/usr/lib/node_modules/uglify-js/bin/uglifyjs:158:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
Error: Unable to compress JavaScript files into '/app/src/../web/bundles/common-temp.js'.
```

Is this related to https://github.com/webpack/webpack/issues/2972#issuecomment-261705632 - the dist files in 1.3.2 don't have `Class` in the code.

**Comment by ksylvest** [comment]
I recompiled with babel / transpilling. It should work with uglify now, but feel free to open an issue if you experience any more issues.

**Comment by schmunk42** [comment]
@ksylvest Thank you! Will check this ... if you want to use a newer JavaScript/ES output in the future, I'd recommend a major version update to avoid issues.
